---
title: "Greenland sensitivity check"
author: "Robbie M Parks"
date: "16/06/2022"
output:
  html_document: 
    toc: yes
  pdf_document: default
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Declare root directory, load folder locations, packages
```{r include=FALSE}
rm(list=ls())

# Declare root directory, load folder locations packages
project.folder <- paste0(print(here::here()),'/')
source(paste0(project.folder,'0_00_create_folder_structure.R'))
source(paste0(file.locations.folder,'file_locations.R'))
source(paste0(packages.folder,'packages_to_load.R'))
```

# options for rstan only
```{r include=FALSE}
options(mc.cores = parallel::detectCores())
rstan_options(auto_write = TRUE)
```

# Load data, rescale pollutants, and view summary
```{r}
source(paste0(models.folder,'c_00_data_loading.R'))
```

# Source model running code
```{r include=FALSE}
source(paste0(models.folder,'c_00_multipollutant_running_code.R'))
```

# Source functions to process results 
```{r include=FALSE}
source(paste0(model.processing.folder,'d_00_model_processing_functions.R'))
```

# run frequentist models for EC + (PM2.5-EC) with and without Greenland
```{r}
# list of datasets
datasets = c('data_1yr','data_5yrs','data_10yrs')

fmlcl = ck ~ 
  family_SES +
  place_birth +
  civst +
  residence +
  EC + PM25

# loop through models and datasets with various models
dat.mean.exp= data.frame()
for(j in c(1:length(datasets))){
  mod.gl = paste0('mod.',datasets[j],'.gl')
  mod.no.gl = paste0('mod.',datasets[j],'.no.gl')
  
  data.gl = get(datasets[j])
  data.no.gl = get(datasets[j]) %>% filter(residence!='Greenland')
  
  assign(mod.gl,clogit_run(fmlcl,data.gl))
  assign(mod.no.gl,clogit_run(fmlcl,data.no.gl))
  
  dat.temp = process_clogit_gl(mod.gl,'EC')
  dat.mean.exp = rbind(dat.mean.exp, dat.temp)
  dat.temp = process_clogit_gl(mod.no.gl,'EC')
  dat.mean.exp = rbind(dat.mean.exp, dat.temp)  
  
  dat.temp = process_clogit_gl(mod.gl,'PM25')
  dat.mean.exp = rbind(dat.mean.exp, dat.temp)
  dat.temp = process_clogit_gl(mod.no.gl,'PM25')
  dat.mean.exp = rbind(dat.mean.exp, dat.temp) 
}
``` 

# Plot results
```{r}

p = ggplot(data=dat.mean.exp) +
    geom_point(aes(x=mod,y=odds.mean),size=1,shape=16, position=position_dodge(width=0.5)) +
    geom_errorbar(aes(x=mod,ymax=odds.ul,ymin=odds.ll),width=.2,size=0.5, position=position_dodge(width=0.5)) +
    facet_grid(~pollutant) +
    geom_hline(yintercept=0,linetype='dotted') +
    xlab('Model') + ylab('Percentage change in odds of ALS diagnosis per SD increase') +
    scale_y_continuous(labels=scales::percent_format(accuracy=1)) +
    scale_x_discrete(labels = ggplot2:::parse_safe) + 
    coord_flip() +
    labs(colour="") +
    guides(colour=guide_legend(nrow=4,byrow=TRUE)) +
    theme_bw() + theme(text = element_text(size = 20),legend.text=element_text(size=7.5),
    panel.grid.major = element_blank(),axis.text.x = element_text(angle=0), axis.text.y = element_text(size=20),
    plot.title = element_text(hjust = 0.5), panel.background = element_blank(),
    panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"),
    panel.border = element_rect(colour = "black"),strip.background = element_blank(),
    legend.position = 'bottom',legend.justification='center',
    legend.background = element_rect(fill="white", size=.5, linetype="dotted"))

print(p)
```

# Plot Greeland against no Greenland
```{r}
dat.mean.exp.gl = dat.mean.exp %>%
  filter(!grepl('no.gl', mod)) %>%
  rename(odds.mean.gl = odds.mean, odds.ll.gl = odds.ll, odds.ul.gl=odds.ul)
dat.mean.exp.no.gl = dat.mean.exp %>%
  filter(grepl('no.gl', mod)) %>%
  select(-stats, -pollutant,-mod) %>%
  rename(odds.mean.no.gl = odds.mean, odds.ll.no.gl = odds.ll, odds.ul.no.gl=odds.ul)
dat.mean.compare = cbind(dat.mean.exp.gl,dat.mean.exp.no.gl)


p = ggplot(data=dat.mean.compare) +
    geom_point(aes(x=odds.mean.gl,y=odds.mean.no.gl),size=1,shape=16) +
    geom_errorbar(aes(x=odds.mean.gl,ymax=odds.ul.no.gl,ymin=odds.ll.no.gl),width=0,size=0.5) +
    geom_errorbarh(aes(y=odds.mean.no.gl,xmax=odds.ul.gl,xmin=odds.ll.gl),width=0,size=0.5) +
    geom_abline() +
    facet_grid(~pollutant) +
    geom_hline(yintercept=0,linetype='dotted') +
    geom_vline(xintercept=0,linetype='dotted') +
    xlab('With Greenland') + ylab('No Greenland') +
    scale_y_continuous(labels=scales::percent_format(accuracy=1)) +
    scale_x_continuous(labels=scales::percent_format(accuracy=1)) +
    coord_equal() + 
    guides(colour=guide_legend(nrow=4,byrow=TRUE)) +
    theme_bw() + theme(text = element_text(size = 20),legend.text=element_text(size=7.5),
    panel.grid.major = element_blank(),axis.text.x = element_text(angle=0), axis.text.y = element_text(size=20),
    plot.title = element_text(hjust = 0.5), panel.background = element_blank(),
    panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"),
    panel.border = element_rect(colour = "black"),strip.background = element_blank(),
    legend.position = 'bottom',legend.justification='center',
    legend.background = element_rect(fill="white", size=.5, linetype="dotted"))

print(p)
```