---
title: "Table 2 for paper (third revision)"
author: "Robbie M Parks"
date: "16/06/2022"
output:
  html_document: 
    toc: yes
  pdf_document: default
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Declare root directory, load folder locations, packages
```{r include=FALSE}
rm(list=ls())

# Declare root directory, load folder locations packages
project.folder <- paste0(print(here::here()),'/')
source(paste0(project.folder,'0_00_create_folder_structure.R'))
source(paste0(file.locations.folder,'file_locations.R'))
source(paste0(packages.folder,'packages_to_load.R'))
```

# Load data
```{r include=FALSE}
source(paste0(models.folder,'c_00_data_loading_non_standardised.R'))
```

# Table 2 prepare
```{r include=FALSE}
# This link is super useful 
# http://www.danieldsjoberg.com/gtsummary/articles/tbl_summary.html
table_2_1yr = data_1yr %>%  
  ungroup(nr) %>%
  dplyr::select(ck, NOX, CO, EC, PM25, O3) %>%
  mutate(ck=recode_factor(ck, 
         `1`='Case',
         `0`='Control')) %>%
  tbl_summary(missing = "no",
              label = list(NOX ~ "NOX",
                           CO ~ "CO",
                           EC ~ "EC",
                           PM25 ~ "non-EC PM2.5",
                           O3 ~ "O3"),
              by = ck,
              statistic = list(all_continuous() ~ "{mean} ({sd})")) %>% 
  modify_header(label ~ "**Pollutant**") %>%
  add_overall() %>%
  bold_labels()

table_2_5yrs = data_5yrs %>%  
  ungroup(nr) %>%
  dplyr::select(ck, NOX, CO, EC, PM25, O3) %>%
  mutate(ck=recode_factor(ck, 
         `1`='Case',
         `0`='Control')) %>%
  tbl_summary(missing = "no",
              label = list(NOX ~ "NOX",
                           CO ~ "CO",
                           EC ~ "EC",
                           PM25 ~ "non-EC PM2.5",
                           O3 ~ "O3"),
              by = ck,
              statistic = list(all_continuous() ~ "{mean} ({sd})")) %>% 
  modify_header(label ~ "**Pollutant**") %>%
  add_overall() %>%
  bold_labels()

table_2_10yrs = data_10yrs %>%  
  ungroup(nr) %>%
  dplyr::select(ck, NOX, CO, EC, PM25, O3) %>%
  mutate(ck=recode_factor(ck, 
         `1`='Case',
         `0`='Control')) %>%
  tbl_summary(missing = "no",
              label = list(NOX ~ "NOX",
                           CO ~ "CO",
                           EC ~ "EC",
                           PM25 ~ "non-EC PM2.5",
                           O3 ~ "O3"),
              by = ck,
              statistic = list(all_continuous() ~ "{mean} ({sd})")) %>% 
  modify_header(label ~ "**Pollutant**") %>%
  add_overall() %>%
  bold_labels()
```

# Table 2 save as Word output
```{r include=FALSE}
table_2_1yr %>%
  as_flex_table() %>%
  flextable::save_as_docx(path = paste0(table2.folder,'table2_1yr.docx'))

table_2_5yrs %>%
  as_flex_table() %>%
  flextable::save_as_docx(path = paste0(table2.folder,'table2_5yrs.docx'))

table_2_10yrs %>%
  as_flex_table() %>%
  flextable::save_as_docx(path = paste0(table2.folder,'table_2_10yrs.docx'))
```

# Table 2 save as gt
```{r include=TRUE}
table_2_1yr %>%
  as_gt() %>%
  tab_header(title = "Pollutant concentrations")

table_2_5yrs %>%
  as_gt() %>%
  tab_header(title = "Pollutant concentrations")

table_2_10yrs %>%
  as_gt() %>%
  tab_header(title = "Pollutant concentrations")
```
