---
title: "Figure 1 for paper"
author: "Robbie M Parks"
date: "16/06/2022"
output:
  html_document: 
    toc: yes
  pdf_document: default
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Declare root directory, load folder locations, packages
```{r include=FALSE}
rm(list=ls())

# Declare root directory, load folder locations packages
project.folder <- paste0(print(here::here()),'/')
source(paste0(project.folder,'0_00_create_folder_structure.R'))
source(paste0(file.locations.folder,'file_locations.R'))
source(paste0(packages.folder,'packages_to_load.R'))
```

# Load data
```{r include=FALSE}
source(paste0(models.folder,'c_00_data_loading_non_standardised.R'))
```

# Figure 1 prepare

# Correlation heatmap for cases and controls together 
```{r}
data_5yrs_pollutants = data_5yrs %>%
  ungroup(nr) %>%
  select(NOX,CO,EC,PM25,O3)

names = c('NO[X]','CO', 'EC', expression(atop('non-EC','PM'[2.5])),'O[3]')
  
colnames(data_5yrs_pollutants) = names

v.matrix <- round(cor(data_5yrs_pollutants, use = "pairwise.complete.obs", 
                    method = c("pearson")),2)

v.matrix[upper.tri(v.matrix)] <- NA          

viz.cormat <- reshape2::melt(v.matrix, na.rm = TRUE) %>% 
  dplyr::rename(Correlation = value) 

# Visualization
cases_and_controls <- viz.cormat %>%
    ggplot(aes(Var1, Var2, fill = Correlation)) +
      geom_tile(color = "white") +
      scale_fill_gradient2(low = "light blue", high = "red", mid = "white", 
        midpoint = 0.5,  space = "Lab", name = "Person\nCorrelation") +
      scale_x_discrete(labels = scales::label_parse()) +
      scale_y_discrete(labels = scales::label_parse()) +
      ggtitle('Overall') + coord_equal() +
      geom_text(aes(Var1, Var2, label = Correlation), color = "black", size = 5) +
      theme(
        axis.text.x = element_text(angle = 45, vjust = 1, size = 12, hjust = 1),
        axis.text.y = element_text(vjust = 1, size = 12, hjust = 1),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        panel.grid.major = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank(),
        axis.ticks = element_blank(),
        legend.direction = "horizontal",
        legend.text = element_text(size = 10),
        legend.title = element_text(size = 10),
        legend.position = "None") 
```

# Correlation heatmap for cases
```{r}
data_5yrs_pollutants = data_5yrs %>%
  filter(ck==1) %>%
  ungroup(nr) %>%
  select(NOX,CO,EC,PM25,O3)

colnames(data_5yrs_pollutants) = names

v.matrix <- round(cor(data_5yrs_pollutants, use = "pairwise.complete.obs", 
                    method = c("pearson")),2)

v.matrix[upper.tri(v.matrix)] <- NA          

viz.cormat <- reshape2::melt(v.matrix, na.rm = TRUE) %>% 
  dplyr::rename(Correlation = value) 

#Visualization
cases <- viz.cormat %>%
    ggplot(aes(Var1, Var2, fill = Correlation)) +
      geom_tile(color = "white") +
      scale_fill_gradient2(low = "light blue", high = "red", mid = "white", 
        midpoint = 0.5,  space = "Lab",name = "Person\nCorrelation") +
      scale_x_discrete(labels = scales::label_parse()) +
      scale_y_discrete(labels = scales::label_parse()) +
    ggtitle('Cases') + coord_equal() +
    geom_text(aes(Var1, Var2, label = Correlation), color = "black", size = 5) +
    theme(
      axis.text.x = element_text(angle = 45, vjust = 1, size = 12, hjust = 1),
      axis.text.y = element_text(vjust = 1, size = 12, hjust = 1),
      axis.title.x = element_blank(),
      axis.title.y = element_blank(),
      panel.grid.major = element_blank(),
      panel.border = element_blank(),
      panel.background = element_blank(),
      axis.ticks = element_blank(),
      legend.direction = "horizontal",
      legend.text = element_text(size = 10),
      legend.title = element_text(size = 10),
      legend.position = "None") 
```

# Correlation heatmap for controls
```{r}
data_5yrs_pollutants = data_5yrs %>%
  filter(ck==0) %>%
  ungroup(nr) %>%
  select(NOX,CO,EC,PM25,O3)

colnames(data_5yrs_pollutants) = names

v.matrix <- round(cor(data_5yrs_pollutants, use = "pairwise.complete.obs", 
                    method = c("pearson")),2)

v.matrix[upper.tri(v.matrix)] <- NA          

viz.cormat <- reshape2::melt(v.matrix, na.rm = TRUE) %>% 
  dplyr::rename(Correlation = value) 

#Visualization
controls <- viz.cormat %>%
    ggplot(aes(Var1, Var2, fill = Correlation)) +
    geom_tile(color = "white") +
    scale_fill_gradient2(low = "light blue", high = "red", mid = "white", 
      midpoint = 0.5,  space = "Lab", name = "Person\nCorrelation") +
      scale_x_discrete(labels = scales::label_parse()) +
      scale_y_discrete(labels = scales::label_parse()) +
    ggtitle('Controls') + coord_equal() +
    geom_text(aes(Var1, Var2, label = Correlation), color = "black", size = 5) +
    theme(
      axis.text.x = element_text(angle = 45, vjust = 1, size = 12, hjust = 1),
      axis.text.y = element_text(vjust = 1, size = 12, hjust = 1),
      axis.title.x = element_blank(),
      axis.title.y = element_blank(),
      panel.grid.major = element_blank(),
      panel.border = element_blank(),
      panel.background = element_blank(),
      axis.ticks = element_blank(),
      legend.direction = "horizontal",
      legend.text = element_text(size = 10),
      legend.title = element_text(size = 10),
      legend.position = "None") 
```

# Save output of plots
```{r}
pdf(paste0(figure1.folder,'figure1.pdf'),paper='a4r',width=0,height=0)
grid.arrange(cases_and_controls,cases,controls,nrow=1)
dev.off()
grid.arrange(cases_and_controls,cases,controls,nrow=1)
```